// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RabbitCHInterface is an autogenerated mock type for the RabbitCHInterface type
type RabbitCHInterface struct {
	mock.Mock
}

// Publisher provides a mock function with given fields: eX, routKey, productJsonString
func (_m *RabbitCHInterface) Publisher(eX string, routKey string, productJsonString []byte) error {
	ret := _m.Called(eX, routKey, productJsonString)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = rf(eX, routKey, productJsonString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
